### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by CuDecker** [CuDecker/MI-449-SS17-740-css-spacing-and-layout-T7bJIb#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://deckercu-kapm87bvfi5cut7bjib.surge.sh/) and meets the following criteria:

- [x] Demonstrate an understanding of the CSS we've learned so far in the class
- [x] Use Flexbox to create the layout of your page
- [x] Use `margin` and `padding` to create space in and between elements
- [x] Use display `block` and `inline-block` properly
- [x] Have fun and do your best to make it pretty, the result should be something you would show to a future employer

I am not sure if I technically did step two (use flexbox to create a layout) 
I used flexbox inside the page. but didn't use flexbox to set up the whole thing?
I'm not sure if that makes total sense.

The display block I used on the facebook and linkedIn portion.  and the inline-block with all the picturessssss

Let me know if all of this works.

**Comment by stuartpearman** [comment]
Hey Curtis, me and Katie traded around some of our code reviews.

I would say all looks good here, I would spend some time creating a little extra space between your elements, everything is a little close together.

Let me know if you have any questions, or if you want help doing something specific, let me know and I can do my best to help!

**Comment by CuDecker** [comment]
@stuartpearman I took what both you and Katie spoke about.

I fixed the spacing adding a lot more spacing to the top of each div element and added just a little between the headings and the pictures. 

Katie explained that what I was doing keeping the spacing equal between the headers and each image made it a bit confusing because it was harder to understand what header went to what image. So I fixed that!

**Comment by KatieMFritz** [comment]
Hi Curtis, I'm jumping in while Stuart is busy. 😁 

The Hobbies section is looking really nice - great job with the spacing! :fire:

The intro section still looks crowded to me. I think I would expect the image to follow the same grid as the text - flag me down and I can show you what I mean. 

I'm getting a console error for `javascript.js`. I think your webfonts might also not be loading properly. This is off to a really awesome start, so I'd love of your to take a little more time to get it working 100%. I'm happy to help!

**Comment by CuDecker** [comment]
Hey @KatieMFritz @stuartpearman , Happy Easterrrr!  I found some spare time and realized that I didn't finish this yet.

It's all fixed nowww! :D 

Have a super day/night!

**Comment by stuartpearman** [comment]
Hey Curtis, I'm still seeing that your fonts aren't showing up properly. Are you using a webfont, or are you using fonts you have on your computer?

**Comment by CuDecker** [comment]
Oooooh fonts on my computer. That would explain why I didn't see the error. and thus didn't change anything.

I removed the font and added some of my least favorite fonts there.

It should be working now? 

Thankss!

**Comment by stuartpearman** [comment]
Haha perfect, hope using those fonts wasn't too painful for you :shipit:
